// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import Admin__DashboardController from "./admin/dashboard_controller";
application.register("admin--dashboard", Admin__DashboardController);

import Admin__TableController from "./admin/table_controller";
application.register("admin--table", Admin__TableController);

import HelloController from "./hello_controller";
application.register("hello", HelloController);

import Site__CartController from "./site/cart_controller";
application.register("site--cart", Site__CartController);

import Site__CategoriesController from "./site/categories_controller";
application.register("site--categories", Site__CategoriesController);

import Site__ProductsController from "./site/products_controller";
application.register("site--products", Site__ProductsController);
