# RuboCop Configuration

require:
  - rubocop-rspec
  - rubocop-rspec_rails

inherit_gem:
  # Omakase Ruby styling for Rails
  rubocop-rails-omakase: rubocop.yml

  # RuboCop and Syntax Tree serve different purposes, but there is overlap with some of RuboCop's functionality.
  # Syntax Tree provides a RuboCop configuration file to disable rules that are redundant with Syntax Tree.
  syntax_tree: config/rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - "vendor/**/*"
    - "test/fixtures/**/*"
    - "db/**/*"
    - "bin/**/*"
    - "log/**/*"
    - "tmp/**/*"
    - "app/views/**/*"
    - "node_modules/**/*"

# Layout Cops

Layout/LineLength:
  Description: "Limit lines to 115 characters."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#80-character-limits"
  Max: 115

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

# Metrics Cops

Metrics/ClassLength:
  Description: "Avoid classes longer than 300 lines of code."
  Max: 300
  Enabled: true

Metrics/ModuleLength:
  Description: "Avoid modules longer than 300 lines of code."
  Max: 300
  Enabled: true

Metrics/ParameterLists:
  Description: "Pass no more than four parameters into a method."
  Max: 4
  Enabled: true

Metrics/MethodLength:
  Description: "Avoid methods longer than 30 lines of code."
  StyleGuide: "<https://github.com/bbatsov/ruby-style-guide#short-methods>"
  Max: 30
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  CountAsOne: ["array", "hash", "heredoc"]
  Max: 25
  AllowedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group

# Style Cops

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#consistent-string-literals"
  EnforcedStyle: double_quotes
  Enabled: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/PreferredHashMethods:
  EnforcedStyle: verbose

Style/SignalException:
  EnforcedStyle: only_raise

Style/InlineComment:
  Description: "Avoid inline comments."
  Enabled: false

# Rails Cops

Rails/Delegate:
  Description: "Prefer delegate method for delegations."
  Enabled: false

Rails/ActionOrder:
  Enabled: false

# Bundler Cops

Bundler/OrderedGems:
  Enabled: false

# RSpec Cops

RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 3
