# frozen_string_literal: true

require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admin/products/1/stocks" do
  let!(:user) do
    User.create!(
      role: Role.find_or_create_by!(name: "Administrator"),
      gender: "male",
      email: "jd@gmail.com",
      password: "pass123",
      first_name: "John",
      last_name: "Doe"
    )
  end
  let!(:category) { Category.create!(name: "Category") }
  let!(:product) { Product.create!(name: "Product", category:) }

  # This should return the minimal set of attributes required to create a valid
  # Stock. As you add validations to Stock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { size: 10, quantity: 5, product_id: product.id } }

  let(:invalid_attributes) { { size: "" } }

  before { sign_in(user) }

  describe "GET /index" do
    it "renders a successful response" do
      Stock.create! valid_attributes
      get admin_product_stocks_url(product)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      stock = Stock.create! valid_attributes
      get admin_product_stock_url(product, stock)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admin_product_stock_url(product)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      stock = Stock.create! valid_attributes
      get edit_admin_product_stock_url(product, stock)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Stock" do
        expect do
 post admin_product_stocks_url(product), params: { stock: valid_attributes } 
end.to change(
          Stock,
          :count
        ).by(1)
      end

      it "redirects to the created stock" do
        post admin_product_stocks_url(product), params: { stock: valid_attributes }
        expect(response).to redirect_to(admin_product_stock_url(product, Stock.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Stock" do
        expect do
 post admin_product_stocks_url(product), params: { stock: invalid_attributes } 
end.not_to change(
          Stock,
          :count
        )
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admin_product_stocks_url(product), params: { stock: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do # rubocop:disable RSpec/MultipleMemoizedHelpers
      let(:new_attributes) { { quantity: 8 } }

      it "updates the requested stock" do
        stock = Stock.create! valid_attributes
        patch admin_product_stock_url(product, stock), params: { stock: new_attributes }
        stock.reload
        expect(stock.quantity).to eq(8)
      end

      it "redirects to the stock" do
        stock = Stock.create! valid_attributes
        patch admin_product_stock_url(product, stock), params: { stock: new_attributes }
        stock.reload
        expect(response).to redirect_to(admin_product_stock_url(product, stock))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        stock = Stock.create! valid_attributes
        patch admin_product_stock_url(product, stock), params: { stock: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested stock" do
      stock = Stock.create! valid_attributes
      expect { delete admin_product_stock_url(product, stock) }.to change(Stock, :count).by(-1)
    end

    it "redirects to the stocks list" do
      stock = Stock.create! valid_attributes
      delete admin_product_stock_url(product, stock)
      expect(response).to redirect_to(admin_product_stocks_url)
    end
  end
end
